"""Config options: API and Authentication."""

from __future__ import annotations

from inspire.config.schema_models import (
    ConfigOption,
    _parse_bool,
    _parse_float,
    _parse_int,
)

API_OPTIONS: list[ConfigOption] = [
    ConfigOption(
        env_var="INSPIRE_BASE_URL",
        toml_key="api.base_url",
        field_name="base_url",
        description="API base URL",
        default="https://api.example.com",
        category="API",
        scope="global",
    ),
    ConfigOption(
        env_var="INSPIRE_TIMEOUT",
        toml_key="api.timeout",
        field_name="timeout",
        description="API timeout in seconds",
        default=30,
        category="API",
        parser=_parse_int,
        scope="global",
    ),
    ConfigOption(
        env_var="INSPIRE_MAX_RETRIES",
        toml_key="api.max_retries",
        field_name="max_retries",
        description="Maximum API retry attempts",
        default=3,
        category="API",
        parser=_parse_int,
        scope="global",
    ),
    ConfigOption(
        env_var="INSPIRE_RETRY_DELAY",
        toml_key="api.retry_delay",
        field_name="retry_delay",
        description="Delay between retries in seconds",
        default=1.0,
        category="API",
        parser=_parse_float,
        scope="global",
    ),
    ConfigOption(
        env_var="INSPIRE_SKIP_SSL_VERIFY",
        toml_key="api.skip_ssl_verify",
        field_name="skip_ssl_verify",
        description="Skip SSL certificate verification (not recommended)",
        default=False,
        category="API",
        parser=_parse_bool,
        scope="global",
    ),
    ConfigOption(
        env_var="INSPIRE_FORCE_PROXY",
        toml_key="api.force_proxy",
        field_name="force_proxy",
        description="Force use of proxy settings",
        default=False,
        category="API",
        parser=_parse_bool,
        scope="global",
    ),
    ConfigOption(
        env_var="INSPIRE_OPENAPI_PREFIX",
        toml_key="api.openapi_prefix",
        field_name="openapi_prefix",
        description="OpenAPI endpoint path prefix",
        default=None,
        category="API",
        scope="global",
    ),
    ConfigOption(
        env_var="INSPIRE_BROWSER_API_PREFIX",
        toml_key="api.browser_api_prefix",
        field_name="browser_api_prefix",
        description="Browser API endpoint path prefix",
        default=None,
        category="API",
        scope="global",
    ),
    ConfigOption(
        env_var="INSPIRE_AUTH_ENDPOINT",
        toml_key="api.auth_endpoint",
        field_name="auth_endpoint",
        description="Authentication endpoint path",
        default=None,
        category="API",
        scope="global",
    ),
    ConfigOption(
        env_var="INSPIRE_DOCKER_REGISTRY",
        toml_key="api.docker_registry",
        field_name="docker_registry",
        description="Docker registry hostname",
        default=None,
        category="API",
        scope="global",
    ),
]

PROXY_OPTIONS: list[ConfigOption] = [
    ConfigOption(
        env_var="INSPIRE_REQUESTS_HTTP_PROXY",
        toml_key="proxy.requests_http",
        field_name="requests_http_proxy",
        description="HTTP proxy URL for requests/curl style traffic",
        default=None,
        category="Proxy",
        scope="global",
    ),
    ConfigOption(
        env_var="INSPIRE_REQUESTS_HTTPS_PROXY",
        toml_key="proxy.requests_https",
        field_name="requests_https_proxy",
        description="HTTPS proxy URL for requests/curl style traffic",
        default=None,
        category="Proxy",
        scope="global",
    ),
    ConfigOption(
        env_var="INSPIRE_PLAYWRIGHT_PROXY",
        toml_key="proxy.playwright",
        field_name="playwright_proxy",
        description="Proxy URL for Playwright browser automation",
        default=None,
        category="Proxy",
        scope="global",
    ),
    ConfigOption(
        env_var="INSPIRE_RTUNNEL_PROXY",
        toml_key="proxy.rtunnel",
        field_name="rtunnel_proxy",
        description="Proxy URL for rtunnel/SSH ProxyCommand transport",
        default=None,
        category="Proxy",
        scope="global",
    ),
]

AUTH_OPTIONS: list[ConfigOption] = [
    ConfigOption(
        env_var="INSPIRE_USERNAME",
        toml_key="auth.username",
        field_name="username",
        description="Platform username",
        default=None,
        category="Authentication",
        scope="project",
    ),
    ConfigOption(
        env_var="INSPIRE_PASSWORD",
        toml_key="auth.password",
        field_name="password",
        description="Platform password (use env var for security)",
        default=None,
        category="Authentication",
        secret=True,
        scope="global",
    ),
]
