"""Typed synchronous and asynchronous clients for application code.

Client-bound facades and handles belong here; reusable business decisions belong
to inspire.services and wire protocols to inspire.platform. References carry
identity, not credentials or proof of current resource state. The async client
shares business logic and suspends at native I/O boundaries; it is not a pool of
synchronous clients. This remains experimental, with unchanged CLI installation
requirements.
"""

from inspire.services.execution.notebook_transfer import TransferResult
from inspire.services.execution.remote_exec import ExecResult
from inspire.exec_output import iter_output_file

from .models_compute import (
    HPCJob,
    HPCJobRef,
    HPCJobCreateSpec,
    HPCJobPlan,
    HPCJobHandle,
    RayJob,
    RayJobRef,
    RayJobCreateSpec,
    RayJobPlan,
    RayJobHandle,
)
from .exceptions import HPCJobFailedError, RayJobFailedError
from inspire.platform.web.browser_api.notebooks import (
    NotebookImageSizeEstimate,
    NotebookResourceSnapshot,
)
from .models_notebooks import (
    Notebook,
    NotebookRef,
    NotebookCreateSpec,
    NotebookPlan,
    NotebookHandle,
    ImageSaveHandle,
)
from .client import InspireClient
from .async_client import InspireAsyncClient
from .accounts import Accounts, InitResult
from .models_resources import (
    AccountInfo,
    AccountCheck,
    AccountContext,
    Permission,
    APIKeyInfo,
    APIKeyRef,
    ProjectInfo,
    ProjectDetail,
    ProjectOwner,
    ProjectOwnerRef,
    ImageDetail,
    DatasetInfo,
    DatasetDetail,
    DatasetRef,
    DatasetTag,
    DatasetTagRef,
    DatasetVersion,
    DatasetVersionRef,
    DatasetApplication,
    DatasetApplicationRef,
    DatasetValidation,
    ModelInfo,
    ModelRef,
    ModelStatus,
    ModelVersion,
    ModelDeployConfig,
    ResourceAvailability,
    ResourceUsage,
    WorkloadSchedulePolicy,
)
from .models import (
    ResourceRef,
    WorkspaceRef,
    ProjectRef,
    ComputeGroupRef,
    ImageRef,
    QuotaRef,
    JobRef,
    Resource,
    Image,
    Quota,
    QuotaOption,
    ImageSelector,
    Job,
    JobHandle,
    Page,
    JobCreateSpec,
    JobPlan,
    DatasetMount,
    MetricGroup,
    Instance,
    JobEvent,
    LogResult,
    EventResult,
)
from .exceptions import (
    InspireError,
    ConfigurationError,
    AuthenticationError,
    AuthenticationCooldownError,
    ClientClosedError,
    ClientThreadError,
    ValidationError,
    ResourceNotFoundError,
    AmbiguousResourceError,
    ResolutionIncompleteError,
    TransportError,
    SubmissionUncertainError,
    MutationUncertainError,
    WaitTimeoutError,
    JobFailedError,
    NotebookFailedError,
)
from .models_serving import (
    Serving,
    ServingRef,
    ServingCreateSpec,
    ServingPlan,
    ServingHandle,
    Tensorboard,
    TensorboardRef,
    TensorboardCreateSpec,
    TensorboardHandle,
    ImageRegisterHandle,
    ModelRegisterHandle,
)
from .exceptions import ServingFailedError, TensorboardFailedError


from .models_observations import (
    ServingVersion,
    ServingScaleHistoryEntry,
    ServingConfigItem,
    ServingConfigs,
    ServingInvocationCredentials,
    ServingInvocationInfo,
    ServingAPIMetricSeries,
    ServingAPIMetricTimeRange,
    ServingAPIMetrics,
    TensorboardTags,
    TensorboardScalarPoint,
    TensorboardScalarSeries,
    TensorboardScalars,
    RayScalingEvent,
    NotebookRun,
)


__all__ = [
    "AsyncJobHandle",
    "AsyncNotebookHandle",
    "AsyncHPCJobHandle",
    "AsyncRayJobHandle",
    "AsyncServingHandle",
    "AsyncTensorboardHandle",
    "AsyncImageSaveHandle",
    "AsyncImageRegisterHandle",

    "ServingVersion",
    "ServingScaleHistoryEntry",
    "ServingConfigItem",
    "ServingConfigs",
    "ServingInvocationCredentials",
    "ServingInvocationInfo",
    "ServingAPIMetricSeries",
    "ServingAPIMetricTimeRange",
    "ServingAPIMetrics",
    "TensorboardTags",
    "TensorboardScalarPoint",
    "TensorboardScalarSeries",
    "TensorboardScalars",
    "RayScalingEvent",
    "NotebookRun",

    "Accounts",
    "InitResult",
    "ExecResult",
    "TransferResult",
    "iter_output_file",
    "Serving",
    "ServingRef",
    "ServingCreateSpec",
    "ServingPlan",
    "ServingHandle",
    "Tensorboard",
    "TensorboardRef",
    "TensorboardCreateSpec",
    "TensorboardHandle",
    "ImageRegisterHandle",
    "ModelRegisterHandle",
    "ServingFailedError",
    "TensorboardFailedError",
    "HPCJob",
    "HPCJobRef",
    "HPCJobCreateSpec",
    "HPCJobPlan",
    "HPCJobHandle",
    "RayJob",
    "RayJobRef",
    "RayJobCreateSpec",
    "RayJobPlan",
    "RayJobHandle",
    "HPCJobFailedError",
    "RayJobFailedError",
    "NotebookImageSizeEstimate",
    "NotebookResourceSnapshot",
    "Notebook",
    "NotebookRef",
    "NotebookCreateSpec",
    "NotebookPlan",
    "NotebookHandle",
    "ImageSaveHandle",
    "NotebookFailedError",
    "AccountInfo",
    "AccountCheck",
    "AccountContext",
    "Permission",
    "APIKeyInfo",
    "APIKeyRef",
    "ProjectInfo",
    "ProjectDetail",
    "ProjectOwner",
    "ProjectOwnerRef",
    "ImageDetail",
    "DatasetInfo",
    "DatasetDetail",
    "DatasetRef",
    "DatasetTag",
    "DatasetTagRef",
    "DatasetVersion",
    "DatasetVersionRef",
    "DatasetApplication",
    "DatasetApplicationRef",
    "DatasetValidation",
    "ModelInfo",
    "ModelRef",
    "ModelStatus",
    "ModelVersion",
    "ModelDeployConfig",
    "ResourceAvailability",
    "ResourceUsage",
    "WorkloadSchedulePolicy",
    "InspireClient",
    "InspireAsyncClient",
    "ResourceRef",
    "WorkspaceRef",
    "ProjectRef",
    "ComputeGroupRef",
    "ImageRef",
    "QuotaRef",
    "JobRef",
    "Resource",
    "Image",
    "Quota",
    "QuotaOption",
    "ImageSelector",
    "Job",
    "JobHandle",
    "Page",
    "JobCreateSpec",
    "JobPlan",
    "DatasetMount",
    "MetricGroup",
    "Instance",
    "JobEvent",
    "LogResult",
    "EventResult",
    "InspireError",
    "ConfigurationError",
    "AuthenticationError",
    "AuthenticationCooldownError",
    "ClientClosedError",
    "ClientThreadError",
    "ValidationError",
    "ResourceNotFoundError",
    "AmbiguousResourceError",
    "ResolutionIncompleteError",
    "TransportError",
    "SubmissionUncertainError",
    "MutationUncertainError",
    "WaitTimeoutError",
    "JobFailedError",
]

from .async_handles import (
    AsyncJobHandle,
    AsyncNotebookHandle,
    AsyncHPCJobHandle,
    AsyncRayJobHandle,
    AsyncServingHandle,
    AsyncTensorboardHandle,
    AsyncImageSaveHandle,
    AsyncImageRegisterHandle,
)
