"""Environment variable detection and TOML content generation for ``inspire init``."""

from __future__ import annotations

import os

from inspire.config import (
    CONFIG_OPTIONS,
    ConfigOption,
    parse_value,
)


def _detect_env_vars() -> list[tuple[ConfigOption, str]]:
    """Detect which configuration env vars are currently set."""
    detected: list[tuple[ConfigOption, str]] = []
    for option in CONFIG_OPTIONS:
        value = os.getenv(option.env_var)
        if value is not None and value != "":
            detected.append((option, value))
    return detected


def _generate_toml_content(
    detected: list[tuple[ConfigOption, str]], scope_filter: str | None = None
) -> str:
    """Generate TOML configuration file content from detected env vars.

    Secrets are always excluded for security.
    """
    lines = [
        "# Inspire CLI Configuration",
        "# Generated by 'inspire init'",
        "",
    ]

    if scope_filter:
        detected = [(opt, val) for opt, val in detected if opt.scope == scope_filter]

    by_section: dict[str, list[tuple[ConfigOption, str]]] = {}
    for option, value in detected:
        section = option.toml_key.split(".", 1)[0]
        by_section.setdefault(section, []).append((option, value))

    section_order = [
        "auth",
        "api",
        "proxy",
        "job",
        "notebook",
        "tunnel",
    ]

    for section in section_order:
        if section not in by_section:
            continue

        lines.append(f"[{section}]")

        for option, value in by_section[section]:
            key = option.toml_key.split(".", 1)[1]

            if option.secret:
                lines.append(f"# {key} - use env var {option.env_var} for security")
                continue

            parsed = parse_value(option, value)
            if isinstance(parsed, bool):
                toml_value = "true" if parsed else "false"
            elif isinstance(parsed, (int, float)):
                toml_value = str(parsed)
            elif isinstance(parsed, list):
                toml_value = "[" + ", ".join(f'"{item}"' for item in parsed) + "]"
            else:
                toml_value = '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'

            lines.append(f"{key} = {toml_value}")

        lines.append("")

    return "\n".join(lines)
