"""Environment variable detection and TOML content generation for ``inspire init``."""

from __future__ import annotations

import os
import re

import click

from inspire.config import (
    CATEGORY_ORDER,
    CONFIG_OPTIONS,
    ConfigOption,
    parse_value,
)


def _redact_token_like_text(text: str) -> str:
    """Best-effort redaction for rtunnel/Jupyter tokens in logs/config."""
    text = str(text or "")
    if not text:
        return text

    # token=<value>
    text = re.sub(r"(token=)[^\s&'\"]+", r"\1<redacted>", text)
    # /jupyter/<nb>/<token>/proxy/... and /vscode/<nb>/<token>/proxy/...
    text = re.sub(
        r"(/(?:jupyter|vscode)/[^/]+/)([^/]+)(/proxy/)",
        r"\1<redacted>\3",
        text,
    )
    return text


def _detect_env_vars() -> list[tuple[ConfigOption, str]]:
    """Detect which configuration env vars are currently set."""
    detected: list[tuple[ConfigOption, str]] = []
    for option in CONFIG_OPTIONS:
        value = os.getenv(option.env_var)
        if value is not None and value != "":
            detected.append((option, value))
    return detected


def _generate_toml_content(
    detected: list[tuple[ConfigOption, str]], scope_filter: str | None = None
) -> str:
    """Generate TOML configuration file content from detected env vars.

    Secrets are always excluded for security.
    """
    lines = [
        "# Inspire CLI Configuration",
        "# Generated by 'inspire init'",
        "",
    ]

    if scope_filter:
        detected = [(opt, val) for opt, val in detected if opt.scope == scope_filter]

    by_section: dict[str, list[tuple[ConfigOption, str]]] = {}
    for option, value in detected:
        section = option.toml_key.split(".", 1)[0]
        by_section.setdefault(section, []).append((option, value))

    section_order = [
        "auth",
        "api",
        "paths",
        "github",
        "sync",
        "bridge",
        "workspaces",
        "job",
        "notebook",
        "ssh",
        "tunnel",
        "mirrors",
        "other",
    ]

    for section in section_order:
        if section not in by_section:
            continue

        lines.append(f"[{section}]")

        for option, value in by_section[section]:
            key = option.toml_key.split(".", 1)[1]

            if option.secret:
                lines.append(f"# {key} - use env var {option.env_var} for security")
                continue

            parsed = parse_value(option, value)
            if isinstance(parsed, bool):
                toml_value = "true" if parsed else "false"
            elif isinstance(parsed, (int, float)):
                toml_value = str(parsed)
            elif isinstance(parsed, list):
                toml_value = "[" + ", ".join(f'"{item}"' for item in parsed) + "]"
            else:
                toml_value = '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'

            lines.append(f"{key} = {toml_value}")

        lines.append("")

    return "\n".join(lines)


def _format_preview_by_scope(detected: list[tuple[ConfigOption, str]]) -> None:
    """Display migration preview grouped by destination (global/project)."""
    click.echo(click.style("Detected environment variables (grouped by destination):", bold=True))
    click.echo()

    global_opts = [(opt, val) for opt, val in detected if opt.scope == "global"]
    project_opts = [(opt, val) for opt, val in detected if opt.scope == "project"]

    if global_opts:
        click.echo(
            click.style("Global config (~/.config/inspire/config.toml):", fg="cyan", bold=True)
        )

        by_category: dict[str, list[tuple[ConfigOption, str]]] = {}
        for option, value in global_opts:
            by_category.setdefault(option.category, []).append((option, value))

        for category in CATEGORY_ORDER:
            if category not in by_category:
                continue

            click.echo(click.style(f"  {category}", fg="blue"))
            for option, value in by_category[category]:
                env_display = option.env_var.ljust(32)
                if option.secret:
                    value_display = click.style("(excluded - use env var)", fg="white", dim=True)
                else:
                    value_display = value[:40] + "..." if len(value) > 40 else value
                click.echo(f"    {env_display} {value_display}")
        click.echo()

    if project_opts:
        click.echo(click.style("Project config (./.inspire/config.toml):", fg="green", bold=True))

        by_category = {}
        for option, value in project_opts:
            by_category.setdefault(option.category, []).append((option, value))

        for category in CATEGORY_ORDER:
            if category not in by_category:
                continue

            click.echo(click.style(f"  {category}", fg="blue"))
            for option, value in by_category[category]:
                env_display = option.env_var.ljust(32)
                if option.secret:
                    value_display = click.style("(excluded - use env var)", fg="white", dim=True)
                else:
                    value_display = value[:40] + "..." if len(value) > 40 else value
                click.echo(f"    {env_display} {value_display}")
            click.echo()
